### ISSUE TITLE
couldn't find "libsound.so"

### ISSUE THREAD

**Issue by pitrodaparth** [onestravel/playSound#1]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cn.onestravel.ndk.playsound-1/base.apk"],nativeLibraryDirectories=[/data/app/cn.onestravel.ndk.playsound-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libsound.so"

  at org.fmod.core.FmodUtils.<clinit>(FmodUtils.java:63)

please update for same.

**Comment by onestravel** [comment]
"libsound.so" is generated after the build, the build directory is “app\build\intermediates\cmake\debug”

**Comment by onestravel** [comment]
> java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cn.onestravel.ndk.playsound-1/base.apk"],nativeLibraryDirectories=[/data/app/cn.onestravel.ndk.playsound-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libsound.so"
> 
> at org.fmod.core.FmodUtils.(FmodUtils.java:63)
> 
> please update for same.

"libsound.so" is generated after the build, the build directory is “app\build\intermediates\cmake\debug”

**Comment by pitrodaparth** [comment]
thanks
by the way i update bit a code on my pc 
can i send pull request?

**Comment by onestravel** [comment]
yes
